export const WEBHOOK_PAYLOAD = {
  entity: 'event',
  account_id: 'acc_Hq69OG0DTBWypL',
  event: 'payment.captured',
  contains: ['payment'],
  payload: {
    payment: {
      entity: {
        id: 'pay_KD55B13ps2xu5S',
        entity: 'payment',
        amount: 2047200,
        currency: 'INR',
        status: 'captured',
        order_id: 'order_KD54WtBb89DA05',
        invoice_id: null,
        international: false,
        method: 'upi',
        amount_refunded: 0,
        refund_status: null,
        captured: true,
        description: '#KD54OeTW8NCm63',
        card_id: null,
        bank: null,
        wallet: null,
        vpa: 'success@razorpay',
        email: 'gillgurpal699@gmail.com',
        contact: '+919136445089',
        notes: {
          order_type: '',
          buyerId: '',
          sellerId: '',
          packageName: '',
        },
        fee: 47200,
        tax: 7200,
        error_code: null,
        error_description: null,
        error_source: null,
        error_step: null,
        error_reason: null,
        acquirer_data: {
          rrn: '715328302482',
          upi_transaction_id: 'D795F2B337AED8E16940CCD581D9F139',
        },
        created_at: 1662132454,
      },
    },
  },
  created_at: 1662132455,
};
export type Webhook_payload = typeof WEBHOOK_PAYLOAD;
