export enum Routes {
  SignUp = "/auth/signup",
  Upload = "/upload",
  Login = "/auth/login",
  FetchAllNotifications = "/notifications",
  FetchProfile = "/auth/profile",
  FetchPublicProfile = "/profile",
  UpdateBIO = "/profile/bio",
  UpdateDetailedBIO = "/profile/detailed-bio",
  updatePassword = "/profile/password",
  fetchDetails = "/profile/details/access",
  UpdateAllThings = "/profile/update/bulk",
  CreateNewPost = "/postings/create",
  FetchPost = "/postings/fetch",
  FetchCreatedOrders = "/orders/created",
  FetchReceivedOrders = "/orders/received",
  FetchChats = "/chats",
  FetchMessages = "/messages",
  FetchCategories = "/categories/fetch",
  CreateCategories = "/categories/create",
  FetchAllCategories = "/categories/fetch/all",
  MarkOrderAsComplete = "/orders/complete",
  FetchPostsUsingTerms = "/search/term",
  FetchPostsUsingCategory = "/search/category",
  UpdateProfilePicture = "/profile/profile-image",
}
